# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeER <- function(temp, ER24_20) {
    .Call(`_NSmetabolism_computeER`, temp, ER24_20)
}

computeGPP <- function(PAR, lP1, lP2) {
    .Call(`_NSmetabolism_computeGPP`, PAR, lP1, lP2)
}

computeGPP_linear <- function(PAR, lP1) {
    .Call(`_NSmetabolism_computeGPP_linear`, PAR, lP1)
}

compute_rf <- function(temp, pressure, DO, k600) {
    .Call(`_NSmetabolism_compute_rf`, temp, pressure, DO, k600)
}

#' Perform inverse distance weighting with a correction for discharge
#'
#' This function works on a vector of k output sites, where the length
#' of each input list and the input vector Q must be k.
#' For each input site, the corresponding input lists contain vectors of neighbor sites;
#' so for site k with discharge Q[k], vals[[k]] is a vector for the n neighbors of site k.
#'
#' @param vals input values of variable to interpolate
#' @param dist distance from focal point to vals; negative for downstream sites
#' @param nbQ discharge of measured sites
#' @param Q discharge of focal site
#' @return interpolated value of vals
#' @export
idw_river <- function(vals, dist, nbQ, Q) {
    .Call(`_NSmetabolism_idw_river`, vals, dist, nbQ, Q)
}

