# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute gross primary productivity from light (g O2 / [m^2 * day])
#' @details P1 is in units of (W*day)/gO2, P2 is in (m^2 * day) / gO2
#' @param lP1 The log of the slope of the PI curve
#' @param lP2 The log of the saturation term of the PI curve
#' @param data Fixed site data, including at least Q, area, and dx
#' @references Uehlinger U. et al. 2000. Variability of photosynthesis-irradiance curves and
#' 		ecosystem respiration in a small river. Freshwater Biology 44:493-507.
#' @return double; computed GPP 
#' 
#' @export
computeGPP <- function(light, lP1, lP2) {
    .Call(`_NSmetabolism_computeGPP`, light, lP1, lP2)
}

